// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"neon/pkg/models/shared"
	"net/http"
)

// CreateProject201ApplicationJSON - Created a project.
// The project includes a connection URI with a database, password, and role.
// At least one non-protected role is created with a password.
// Wait until the operations are finished before attempting to connect to a project database.
type CreateProject201ApplicationJSON struct {
	Branch         shared.Branch              `json:"branch"`
	ConnectionUris []shared.ConnectionDetails `json:"connection_uris"`
	Databases      []shared.Database          `json:"databases"`
	Endpoints      []shared.Endpoint          `json:"endpoints"`
	Operations     []shared.Operation         `json:"operations"`
	Project        shared.Project             `json:"project"`
	Roles          []shared.Role              `json:"roles"`
}

type CreateProjectResponse struct {
	ContentType string
	// General Error
	GeneralError *shared.GeneralError
	StatusCode   int
	RawResponse  *http.Response
	// Created a project.
	// The project includes a connection URI with a database, password, and role.
	// At least one non-protected role is created with a password.
	// Wait until the operations are finished before attempting to connect to a project database.
	//
	CreateProject201ApplicationJSONObject *CreateProject201ApplicationJSON
}
