// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"neon/pkg/models/shared"
	"net/http"
)

type CreateProjectBranchRequest struct {
	// The Neon project ID
	ProjectID           string                      `pathParam:"style=simple,explode=false,name=project_id"`
	BranchCreateRequest *shared.BranchCreateRequest `request:"mediaType=application/json"`
}

// CreateProjectBranch201ApplicationJSON - Created a branch. An endpoint is only created if it was specified in the request.
type CreateProjectBranch201ApplicationJSON struct {
	Branch         shared.Branch              `json:"branch"`
	ConnectionUris []shared.ConnectionDetails `json:"connection_uris,omitempty"`
	Endpoints      []shared.Endpoint          `json:"endpoints"`
	Operations     []shared.Operation         `json:"operations"`
}

type CreateProjectBranchResponse struct {
	ContentType string
	// General Error
	GeneralError *shared.GeneralError
	StatusCode   int
	RawResponse  *http.Response
	// Created a branch. An endpoint is only created if it was specified in the request.
	CreateProjectBranch201ApplicationJSONObject *CreateProjectBranch201ApplicationJSON
}
