// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"neon/pkg/models/shared"
	"net/http"
)

type DeleteProjectRequest struct {
	// The Neon project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=project_id"`
}

type DeleteProjectResponse struct {
	ContentType string
	// General Error
	GeneralError *shared.GeneralError
	// Deleted the specified project
	ProjectResponse *shared.ProjectResponse
	StatusCode      int
	RawResponse     *http.Response
}
