// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"neon/pkg/models/shared"
	"net/http"
)

type DeleteProjectBranchDatabaseRequest struct {
	// The branch ID
	BranchID string `pathParam:"style=simple,explode=false,name=branch_id"`
	// The database name
	DatabaseName string `pathParam:"style=simple,explode=false,name=database_name"`
	// The Neon project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=project_id"`
}

type DeleteProjectBranchDatabaseResponse struct {
	ContentType string
	// Deleted the specified database
	DatabaseOperations *shared.DatabaseOperations
	// General Error
	GeneralError *shared.GeneralError
	StatusCode   int
	RawResponse  *http.Response
}
