// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"neon/pkg/models/shared"
	"net/http"
)

type GetProjectBranchRolePasswordRequest struct {
	// The branch ID
	BranchID string `pathParam:"style=simple,explode=false,name=branch_id"`
	// The Neon project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=project_id"`
	// The role name
	RoleName string `pathParam:"style=simple,explode=false,name=role_name"`
}

type GetProjectBranchRolePasswordResponse struct {
	ContentType string
	// Role not found
	GeneralError *shared.GeneralError
	// Successfully returned password for the specified role
	RolePasswordResponse *shared.RolePasswordResponse
	StatusCode           int
	RawResponse          *http.Response
}
