// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"neon/pkg/models/shared"
	"net/http"
)

type GetProjectBranchDatabaseRequest struct {
	// The branch ID
	BranchID string `pathParam:"style=simple,explode=false,name=branch_id"`
	// The database name
	DatabaseName string `pathParam:"style=simple,explode=false,name=database_name"`
	// The Neon project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=project_id"`
}

type GetProjectBranchDatabaseResponse struct {
	ContentType string
	// Returned the database details
	DatabaseResponse *shared.DatabaseResponse
	// General Error
	GeneralError *shared.GeneralError
	StatusCode   int
	RawResponse  *http.Response
}
