// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"neon/pkg/models/shared"
	"net/http"
)

type GetProjectBranchRoleRequest struct {
	// The branch ID
	BranchID string `pathParam:"style=simple,explode=false,name=branch_id"`
	// The Neon project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=project_id"`
	// The role name
	RoleName string `pathParam:"style=simple,explode=false,name=role_name"`
}

type GetProjectBranchRoleResponse struct {
	ContentType string
	// General Error
	GeneralError *shared.GeneralError
	// Successfully returned details for the specified role
	RoleResponse *shared.RoleResponse
	StatusCode   int
	RawResponse  *http.Response
}
