// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"neon/pkg/models/shared"
	"net/http"
)

type ListAPIKeysResponse struct {
	// Returned the API keys for the Neon account
	APIKeysListResponseItems []shared.APIKeysListResponseItem
	ContentType              string
	// General Error
	GeneralError *shared.GeneralError
	StatusCode   int
	RawResponse  *http.Response
}
