// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"neon/pkg/models/shared"
	"net/http"
)

type ListProjectOperationsRequest struct {
	// Specify the cursor value from the previous response to get the next batch of operations
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// Specify a value from 1 to 1000 to limit number of operations in the response
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// The Neon project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=project_id"`
}

// ListProjectOperations200ApplicationJSON - Returned a list of operations
type ListProjectOperations200ApplicationJSON struct {
	Operations []shared.Operation `json:"operations"`
	// Cursor based pagination is used. The user must pass the cursor as is to the backend.
	// For more information about cursor based pagination, see
	// https://learn.microsoft.com/en-us/ef/core/querying/pagination#keyset-pagination
	//
	Pagination *shared.Pagination `json:"pagination,omitempty"`
}

type ListProjectOperationsResponse struct {
	ContentType string
	// General Error
	GeneralError *shared.GeneralError
	StatusCode   int
	RawResponse  *http.Response
	// Returned a list of operations
	//
	ListProjectOperations200ApplicationJSONObject *ListProjectOperations200ApplicationJSON
}
