// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"neon/pkg/models/shared"
	"net/http"
)

type ListProjectBranchRolesRequest struct {
	// The branch ID
	BranchID string `pathParam:"style=simple,explode=false,name=branch_id"`
	// The Neon project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=project_id"`
}

type ListProjectBranchRolesResponse struct {
	ContentType string
	// General Error
	GeneralError *shared.GeneralError
	// Returned a list of roles from the specified branch.
	RolesResponse *shared.RolesResponse
	StatusCode    int
	RawResponse   *http.Response
}
