// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"neon/pkg/models/shared"
	"net/http"
)

type ListProjectEndpointsRequest struct {
	// The Neon project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=project_id"`
}

type ListProjectEndpointsResponse struct {
	ContentType string
	// Returned a list of endpoints for the specified project
	EndpointsResponse *shared.EndpointsResponse
	// General Error
	GeneralError *shared.GeneralError
	StatusCode   int
	RawResponse  *http.Response
}
