// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"neon/pkg/models/shared"
	"net/http"
)

type RevokeAPIKeyRequest struct {
	// The API key ID
	KeyID int64 `pathParam:"style=simple,explode=false,name=key_id"`
}

type RevokeAPIKeyResponse struct {
	// Revoked the specified API key
	APIKeyRevokeResponse *shared.APIKeyRevokeResponse
	ContentType          string
	// General Error
	GeneralError *shared.GeneralError
	StatusCode   int
	RawResponse  *http.Response
}
