// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"neon/pkg/models/shared"
	"net/http"
)

type SetPrimaryProjectBranchRequest struct {
	// The branch ID
	BranchID string `pathParam:"style=simple,explode=false,name=branch_id"`
	// The Neon project ID
	ProjectID string `pathParam:"style=simple,explode=false,name=project_id"`
}

type SetPrimaryProjectBranchResponse struct {
	// Updated the specified branch
	BranchOperations *shared.BranchOperations
	ContentType      string
	// General Error
	GeneralError *shared.GeneralError
	StatusCode   int
	RawResponse  *http.Response
}
