// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// APIKeyCreateResponse - Created an API key
type APIKeyCreateResponse struct {
	// The API key ID
	ID int64 `json:"id"`
	// The generated 64-bit token required to access the Neon API
	Key string `json:"key"`
}
