// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// APIKeyRevokeResponse - Revoked the specified API key
type APIKeyRevokeResponse struct {
	// The API key ID
	ID int64 `json:"id"`
	// A timestamp indicating when the API was last used
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	// The IP address from which the API key was last used
	LastUsedFromAddr string `json:"last_used_from_addr"`
	// The user-specified API key name
	Name string `json:"name"`
	// A `true` or `false` value indicating whether the API key is revoked
	Revoked bool `json:"revoked"`
}
