// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type APIKeysListResponseItem struct {
	// A timestamp indicating when the API key was created
	CreatedAt time.Time `json:"created_at"`
	// The API key ID
	ID int64 `json:"id"`
	// A timestamp indicating when the API was last used
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	// The IP address from which the API key was last used
	LastUsedFromAddr string `json:"last_used_from_addr"`
	// The user-specified API key name
	Name string `json:"name"`
}
