// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type APIKeyCreateRequest struct {
	// A user-specified API key name. This value is required when creating an API key.
	KeyName string `json:"key_name"`
}
