// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// BillingSubscriptionType - Type of subscription to Neon Cloud.
// Notice that for users without billing account this will be "UNKNOWN"
type BillingSubscriptionType string

const (
	BillingSubscriptionTypeUnknown             BillingSubscriptionType = "UNKNOWN"
	BillingSubscriptionTypeFree                BillingSubscriptionType = "free"
	BillingSubscriptionTypePro                 BillingSubscriptionType = "pro"
	BillingSubscriptionTypePlatformPartnership BillingSubscriptionType = "platform_partnership"
	BillingSubscriptionTypeEnterprise          BillingSubscriptionType = "enterprise"
)

func (e BillingSubscriptionType) ToPointer() *BillingSubscriptionType {
	return &e
}

func (e *BillingSubscriptionType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "UNKNOWN":
		fallthrough
	case "free":
		fallthrough
	case "pro":
		fallthrough
	case "platform_partnership":
		fallthrough
	case "enterprise":
		*e = BillingSubscriptionType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BillingSubscriptionType: %v", v)
	}
}
