// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// BranchOperations - Deleted the specified branch
type BranchOperations struct {
	Branch     Branch      `json:"branch"`
	Operations []Operation `json:"operations"`
}
