// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type BranchUpdateRequestBranch struct {
	Name *string `json:"name,omitempty"`
}

type BranchUpdateRequest struct {
	Branch BranchUpdateRequestBranch `json:"branch"`
}
