// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// BranchResponse - Returned information about the specified branch
type BranchResponse struct {
	Branch Branch `json:"branch"`
}
