// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type BranchCreateRequestEndpointOptions struct {
	AutoscalingLimitMaxCu *float64 `json:"autoscaling_limit_max_cu,omitempty"`
	AutoscalingLimitMinCu *float64 `json:"autoscaling_limit_min_cu,omitempty"`
	// The Neon compute provisioner.
	//
	Provisioner *Provisioner `json:"provisioner,omitempty"`
	// Duration of inactivity in seconds after which endpoint will be
	// automatically suspended. Value `0` means use global default,
	// `-1` means never suspend. Maximum value is 1 week in seconds.
	//
	SuspendTimeoutSeconds *int64 `json:"suspend_timeout_seconds,omitempty"`
	// The compute endpoint type. Either `read_write` or `read_only`.
	// The `read_only` compute endpoint type is not yet supported.
	//
	Type EndpointType `json:"type"`
}
