// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// BranchesResponse - Returned a list of branches for the specified project
type BranchesResponse struct {
	Branches []Branch `json:"branches"`
}
