// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ConnectionParameters struct {
	// Database name.
	//
	Database string `json:"database"`
	// Host name.
	//
	Host string `json:"host"`
	// Password for the role.
	//
	Password string `json:"password"`
	// Pooler host name.
	//
	PoolerHost string `json:"pooler_host"`
	// Role name.
	//
	Role string `json:"role"`
}
