// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DatabaseResponse - Returned the database details
type DatabaseResponse struct {
	Database Database `json:"database"`
}
