// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type Database struct {
	// The ID of the branch to which the database belongs
	//
	BranchID string `json:"branch_id"`
	// A timestamp indicating when the database was created
	//
	CreatedAt time.Time `json:"created_at"`
	// The database ID
	//
	ID int64 `json:"id"`
	// The database name
	//
	Name string `json:"name"`
	// The name of role that owns the database
	//
	OwnerName string `json:"owner_name"`
	// A timestamp indicating when the database was last updated
	//
	UpdatedAt time.Time `json:"updated_at"`
}
