// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DatabaseCreateRequestDatabase struct {
	// The name of the datbase
	//
	Name string `json:"name"`
	// The name of the role that owns the database
	//
	OwnerName string `json:"owner_name"`
}

type DatabaseCreateRequest struct {
	Database DatabaseCreateRequestDatabase `json:"database"`
}
