// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DatabaseUpdateRequestDatabase struct {
	// The name of the database
	//
	Name *string `json:"name,omitempty"`
	// The name of the role that owns the database
	//
	OwnerName *string `json:"owner_name,omitempty"`
}

type DatabaseUpdateRequest struct {
	Database DatabaseUpdateRequestDatabase `json:"database"`
}
