// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DatabasesResponse - Returned a list of databases of the specified branch
type DatabasesResponse struct {
	Databases []Database `json:"databases"`
}
