// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DatabaseOperations - Created a database in the specified branch
type DatabaseOperations struct {
	Database   Database    `json:"database"`
	Operations []Operation `json:"operations"`
}
