// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DefaultEndpointSettings - A collection of settings for a Neon endpoint
type DefaultEndpointSettings struct {
	// A raw representation of PostgreSQL settings
	PgSettings map[string]string `json:"pg_settings,omitempty"`
}
