// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type EndpointUpdateRequestEndpoint struct {
	AutoscalingLimitMaxCu *float64 `json:"autoscaling_limit_max_cu,omitempty"`
	AutoscalingLimitMinCu *float64 `json:"autoscaling_limit_min_cu,omitempty"`
	// The destination branch ID. The destination branch must not have an exsiting read-write endpoint.
	//
	BranchID *string `json:"branch_id,omitempty"`
	// Whether to restrict connections to the compute endpoint
	//
	Disabled *bool `json:"disabled,omitempty"`
	// NOT YET IMPLEMENTED. Whether to permit passwordless access to the compute endpoint.
	//
	PasswordlessAccess *bool `json:"passwordless_access,omitempty"`
	// Whether to enable connection pooling for the compute endpoint
	//
	PoolerEnabled *bool `json:"pooler_enabled,omitempty"`
	// The connection pooler mode. Neon supports PgBouncer in `transaction` mode only.
	//
	PoolerMode *EndpointPoolerMode `json:"pooler_mode,omitempty"`
	// The Neon compute provisioner.
	//
	Provisioner *Provisioner `json:"provisioner,omitempty"`
	// A collection of settings for a compute endpoint
	Settings *EndpointSettingsData `json:"settings,omitempty"`
	// Duration of inactivity in seconds after which endpoint will be
	// automatically suspended. Value `0` means use global default,
	// `-1` means never suspend. Maximum value is 1 week in seconds.
	//
	SuspendTimeoutSeconds *int64 `json:"suspend_timeout_seconds,omitempty"`
}

type EndpointUpdateRequest struct {
	Endpoint EndpointUpdateRequestEndpoint `json:"endpoint"`
}
