// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// EndpointPoolerMode - The connection pooler mode. Neon supports PgBouncer in `transaction` mode only.
type EndpointPoolerMode string

const (
	EndpointPoolerModeTransaction EndpointPoolerMode = "transaction"
)

func (e EndpointPoolerMode) ToPointer() *EndpointPoolerMode {
	return &e
}

func (e *EndpointPoolerMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "transaction":
		*e = EndpointPoolerMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EndpointPoolerMode: %v", v)
	}
}
