// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EndpointSettingsData - A collection of settings for a compute endpoint
type EndpointSettingsData struct {
	// A raw representation of PostgreSQL settings
	PgSettings map[string]string `json:"pg_settings,omitempty"`
}
