// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EndpointResponse - Returned information about the specified endpoint
type EndpointResponse struct {
	Endpoint Endpoint `json:"endpoint"`
}
