// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EndpointOperations - Created an endpoint
type EndpointOperations struct {
	Endpoint   Endpoint    `json:"endpoint"`
	Operations []Operation `json:"operations"`
}
