// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EndpointsResponse - Returned a list of endpoints for the specified branch
type EndpointsResponse struct {
	Endpoints []Endpoint `json:"endpoints"`
}
