// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GeneralError - General Error
type GeneralError struct {
	Code string `json:"code"`
	// Error message
	Message string `json:"message"`
}
