// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type Operation struct {
	// The action performed by the operation
	Action OperationAction `json:"action"`
	// The branch ID
	BranchID *string `json:"branch_id,omitempty"`
	// A timestamp indicating when the operation was created
	CreatedAt time.Time `json:"created_at"`
	// The endpoint ID
	EndpointID *string `json:"endpoint_id,omitempty"`
	// The error that occured
	Error *string `json:"error,omitempty"`
	// The number of times the operation failed
	FailuresCount int `json:"failures_count"`
	// The operation ID
	ID string `json:"id"`
	// The Neon project ID
	ProjectID string `json:"project_id"`
	// A timestamp indicating when the operation was last retried
	RetryAt *time.Time `json:"retry_at,omitempty"`
	// The status of the operation
	Status OperationStatus `json:"status"`
	// A timestamp indicating when the operation status was last updated
	UpdatedAt time.Time `json:"updated_at"`
}
