// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// OperationResponse - Returned details for the specified operation
type OperationResponse struct {
	Operation Operation `json:"operation"`
}
