// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// OperationStatus - The status of the operation
type OperationStatus string

const (
	OperationStatusRunning    OperationStatus = "running"
	OperationStatusFinished   OperationStatus = "finished"
	OperationStatusFailed     OperationStatus = "failed"
	OperationStatusScheduling OperationStatus = "scheduling"
)

func (e OperationStatus) ToPointer() *OperationStatus {
	return &e
}

func (e *OperationStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "running":
		fallthrough
	case "finished":
		fallthrough
	case "failed":
		fallthrough
	case "scheduling":
		*e = OperationStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OperationStatus: %v", v)
	}
}
