// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ProjectCreateRequestProjectBranch struct {
	// The database name. If not specified, the default database name will be used.
	//
	DatabaseName *string `json:"database_name,omitempty"`
	// The branch name. If not specified, the default branch name will be used.
	//
	Name *string `json:"name,omitempty"`
	// The role name. If not specified, the default role name will be used.
	//
	RoleName *string `json:"role_name,omitempty"`
}

type ProjectCreateRequestProject struct {
	AutoscalingLimitMaxCu *float64                           `json:"autoscaling_limit_max_cu,omitempty"`
	AutoscalingLimitMinCu *float64                           `json:"autoscaling_limit_min_cu,omitempty"`
	Branch                *ProjectCreateRequestProjectBranch `json:"branch,omitempty"`
	// A raw representation of PostgreSQL settings
	DefaultEndpointSettings map[string]string `json:"default_endpoint_settings,omitempty"`
	// The project name
	Name *string `json:"name,omitempty"`
	// The major PostgreSQL version number. Currently supported version are `14` and `15`.
	PgVersion *int64 `json:"pg_version,omitempty"`
	// The Neon compute provisioner.
	//
	Provisioner *Provisioner `json:"provisioner,omitempty"`
	// The region identifier. See [the documentation](https://neon.tech/docs/introduction/regions) for the list of supported regions.
	//
	RegionID *string              `json:"region_id,omitempty"`
	Settings *ProjectSettingsData `json:"settings,omitempty"`
	// Whether or not passwords are stored for roles in the Neon project. Storing passwords facilitates access to Neon features that require authorization.
	//
	StorePasswords *bool `json:"store_passwords,omitempty"`
}

type ProjectCreateRequest struct {
	Project ProjectCreateRequestProject `json:"project"`
}
