// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ProjectResponse - Deleted the specified project
type ProjectResponse struct {
	Project Project `json:"project"`
}
