// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ProjectOperations - Updated the specified project
type ProjectOperations struct {
	Operations []Operation `json:"operations"`
	Project    Project     `json:"project"`
}
