// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ProjectUpdateRequestProject struct {
	// A raw representation of PostgreSQL settings
	DefaultEndpointSettings map[string]string    `json:"default_endpoint_settings,omitempty"`
	Name                    *string              `json:"name,omitempty"`
	Settings                *ProjectSettingsData `json:"settings,omitempty"`
}

type ProjectUpdateRequest struct {
	Project ProjectUpdateRequestProject `json:"project"`
}
