// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ProjectOwnerData struct {
	BranchesLimit int64  `json:"branches_limit"`
	Email         string `json:"email"`
	// Type of subscription to Neon Cloud.
	// Notice that for users without billing account this will be "UNKNOWN"
	//
	SubscriptionType BillingSubscriptionType `json:"subscription_type"`
}
