// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// Provisioner - The Neon compute provisioner.
type Provisioner string

const (
	ProvisionerK8sPod    Provisioner = "k8s-pod"
	ProvisionerK8sNeonvm Provisioner = "k8s-neonvm"
)

func (e Provisioner) ToPointer() *Provisioner {
	return &e
}

func (e *Provisioner) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "k8s-pod":
		fallthrough
	case "k8s-neonvm":
		*e = Provisioner(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Provisioner: %v", v)
	}
}
