// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RoleResponse - Successfully returned details for the specified role
type RoleResponse struct {
	Role Role `json:"role"`
}
