// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RoleOperations - Created a role in the specified branch
type RoleOperations struct {
	Operations []Operation `json:"operations"`
	Role       Role        `json:"role"`
}
