// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RolesResponse - Returned a list of roles from the specified branch.
type RolesResponse struct {
	Roles []Role `json:"roles"`
}
