// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type Role struct {
	// The ID of the branch to which the role belongs
	//
	BranchID string `json:"branch_id"`
	// A timestamp indicating when the role was created
	//
	CreatedAt time.Time `json:"created_at"`
	// The role name
	//
	Name string `json:"name"`
	// The role password
	//
	Password *string `json:"password,omitempty"`
	// Whether or not the role is system-protected
	//
	Protected *bool `json:"protected,omitempty"`
	// A timestamp indicating when the role was last updated
	//
	UpdatedAt time.Time `json:"updated_at"`
}
