// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RolePasswordResponse - Successfully returned password for the specified role
type RolePasswordResponse struct {
	// The role password
	//
	Password string `json:"password"`
}
